server:
  servlet:
    context-path: /openapi/dev
  port: 8080
---
environment: dev
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    activate.on-profile: td-bkdtdvar-chnge
    name: td-bkdtdvar-chnge-YAML
  jms:
    useAsyncSend: true
  activemq:
    broker-url: ${NGI_JMS_BROKER_URL}
    concurrency: 3-10
    timeout: 10000
  audit-datasource:
    url: ${NGI_AUDITDB_ADDRESS}
    username: ${NGI_AUDITDB_USERNAME}
    password: ${NGI_AUDITDB_PASSWORD}
    schema: ${NGI_AUDITDB_SCHEMA}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-wait: 20000
      max-active: 300
      max-idle: 10
      min-idle: 5
      initial-size: 10
      test-on-connect: true
      test-on-borrow: true
      validation-query: SELECT 1 from DUAL
      validation-query-timeout: 10
      validation-interval: 15000
      remove-abandoned: true
      remove-abandoned-timeout: 30
      jmx-enabled: true
  main-datasource:
    url: ${NGI_MAINDB_ADDRESS}
    username: ${NGI_MAINDB_USERNAME}
    password: ${NGI_MAINDB_PASSWROD}
    schema: ${NGI_MAINDB_SCHEMA}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-wait: 20000
      max-active: 300
      max-idle: 10
      min-idle: 5
      initial-size: 10
      test-on-connect: true
      test-on-borrow: true
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 10
      validation-interval: 15000
      remove-abandoned: true
      remove-abandoned-timeout: 30
      jmx-enabled: true

  jpa:
    timeout-sec: 30
    generate-ddl: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    root: error
    web: error
    org:
      hibernate: info
      springframework: info
      apache.tomcat.jdbc.pool: info
    com.oracle.fcr.ngi: error


rest:
  config:
    timeout-millis: 30000



jasypt:
  encryptor:
    password: ${NGI_JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES

log:
  rest-base-url: http://ngi-log:8080/openapi/dev
  audit:
    type: jms # database, rest, or jms
    designation-name: ngi-audit-log-queue
  interface:
    type: jms # database, rest, or jms
    designation-name: ngi-interface-log-queue
  sequence-name: NGI_TDM48_AUDIT_SEQUENCE
  trace-id-prefix: BKDTINTRVAR


# Actuators properties
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*' # ["metrics", "prometheus", "circuitbreakers", "circuitbreakerevents"]
  endpoint:
    health:
      show-details: always

# resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      td-bkdtdvar-chnge:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      td-bkdtdvar-chnge:
        cancelRunningFuture: true
        timeoutDuration: 5s      

allowedUsers: "APIINTOPR"
